#!/usr/bin/env python

from rq import Connection, Worker
from src.helpers.job_helper import handle_job_failure


with Connection():
    w = Worker(['default'])
    w.push_exc_handler(handle_job_failure)
    w.work()