#!/bin/bash

# Start appropriate process based on it's env role. One of 3 options:
# (1) Worker
# (2) Migrations
# (3) Server (default)

if [[ $CORE_ROLE == "worker" ]]; then
    python -m src.initializers.export_clusters
    chmod +x ./job_worker
    ./job_worker -c worker_config
elif [[ $CORE_ROLE == "migration" ]]; then
    python manage.py db upgrade
else
    /usr/bin/supervisord
fi