"""empty message

Revision ID: 0042ab9a819d
Revises: 218412f6ef99
Create Date: 2018-01-21 15:23:36.045754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0042ab9a819d'
down_revision = '218412f6ef99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_repo_id'), 'env', ['repo_id'], unique=False)
    op.create_index(op.f('ix_env_uid'), 'env', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_env_uid'), table_name='env')
    op.drop_index(op.f('ix_env_repo_id'), table_name='env')
    op.drop_table('env')
    # ### end Alembic commands ###
