"""empty message

Revision ID: 1d5588e7799d
Revises: 3e72ec83e74a
Create Date: 2018-01-08 20:01:07.939656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5588e7799d'
down_revision = '3e72ec83e74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_provider_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('provider_user_id', sa.Integer(), nullable=False),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_provider_user_provider_user_id'), 'team_provider_user', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_team_provider_user_team_id'), 'team_provider_user', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_provider_user_team_id'), table_name='team_provider_user')
    op.drop_index(op.f('ix_team_provider_user_provider_user_id'), table_name='team_provider_user')
    op.drop_table('team_provider_user')
    # ### end Alembic commands ###
