"""empty message

Revision ID: 26ba6c4aedba
Revises: db537da603ae
Create Date: 2017-12-24 15:50:45.732922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26ba6c4aedba'
down_revision = 'db537da603ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_slug'), 'integration', ['slug'], unique=True)
    op.create_index(op.f('ix_integration_uid'), 'integration', ['uid'], unique=True)
    op.create_table('prediction_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=360), nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_integration_integration_id'), 'prediction_integration', ['integration_id'], unique=False)
    op.create_index(op.f('ix_prediction_integration_prediction_id'), 'prediction_integration', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_prediction_integration_uid'), 'prediction_integration', ['uid'], unique=True)
    op.create_table('prediction_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('retrain_on_merge', sa.Boolean(), server_default='f', nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_setting_prediction_id'), 'prediction_setting', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_setting_prediction_id'), table_name='prediction_setting')
    op.drop_table('prediction_setting')
    op.drop_index(op.f('ix_prediction_integration_uid'), table_name='prediction_integration')
    op.drop_index(op.f('ix_prediction_integration_prediction_id'), table_name='prediction_integration')
    op.drop_index(op.f('ix_prediction_integration_integration_id'), table_name='prediction_integration')
    op.drop_table('prediction_integration')
    op.drop_index(op.f('ix_integration_uid'), table_name='integration')
    op.drop_index(op.f('ix_integration_slug'), table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
