"""empty message

Revision ID: 286624a8f5a0
Revises: fc426eb65a5a
Create Date: 2017-11-27 17:17:43.527813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '286624a8f5a0'
down_revision = 'fc426eb65a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.alter_column('bucket', 'name',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.drop_column('cluster', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('bucket', 'name',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    # ### end Alembic commands ###
