"""empty message

Revision ID: 3265dc895d3e
Revises: 5e0d3c8f7191
Create Date: 2018-01-31 17:03:31.066380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3265dc895d3e'
down_revision = '5e0d3c8f7191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('x_axis', sa.String(), nullable=False),
    sa.Column('y_axis', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_deployment_id'), 'graph', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_graph_uid'), 'graph', ['uid'], unique=True)
    op.create_table('graph_data_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('graph_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graph.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_data_group_graph_id'), 'graph_data_group', ['graph_id'], unique=False)
    op.create_index(op.f('ix_graph_data_group_uid'), 'graph_data_group', ['uid'], unique=True)
    op.create_table('graph_data_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_data_group_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['graph_data_group_id'], ['graph_data_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_data_point_graph_data_group_id'), 'graph_data_point', ['graph_data_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_data_point_graph_data_group_id'), table_name='graph_data_point')
    op.drop_table('graph_data_point')
    op.drop_index(op.f('ix_graph_data_group_uid'), table_name='graph_data_group')
    op.drop_index(op.f('ix_graph_data_group_graph_id'), table_name='graph_data_group')
    op.drop_table('graph_data_group')
    op.drop_index(op.f('ix_graph_uid'), table_name='graph')
    op.drop_index(op.f('ix_graph_deployment_id'), table_name='graph')
    op.drop_table('graph')
    # ### end Alembic commands ###
