"""empty message

Revision ID: 372006436917
Revises: 814ec150634c
Create Date: 2018-01-15 13:23:12.405389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372006436917'
down_revision = '814ec150634c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('serve_triggered_by', sa.String(length=120), nullable=True))
    op.add_column('deployment', sa.Column('train_triggered_by', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'train_triggered_by')
    op.drop_column('deployment', 'serve_triggered_by')
    # ### end Alembic commands ###
