"""empty message

Revision ID: 454e67e0223a
Revises: bf2068f5b244
Create Date: 2017-12-23 20:18:48.481201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454e67e0223a'
down_revision = 'bf2068f5b244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_job_deployment_id'), 'train_job', ['deployment_id'], unique=False)
    op.add_column(u'dataset', sa.Column('last_train_record_count', sa.Integer(), nullable=True))
    op.add_column(u'dataset', sa.Column('retrain_step_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'dataset', 'retrain_step_size')
    op.drop_column(u'dataset', 'last_train_record_count')
    op.drop_index(op.f('ix_train_job_deployment_id'), table_name='train_job')
    op.drop_table('train_job')
    # ### end Alembic commands ###
