"""empty message

Revision ID: 5e0d3c8f7191
Revises: 8610df01cf2a
Create Date: 2018-01-25 20:37:14.460040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0d3c8f7191'
down_revision = '8610df01cf2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('seen_basic_auth_prompt', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seen_basic_auth_prompt')
    # ### end Alembic commands ###
