"""empty message

Revision ID: 6a2ec879943f
Revises: 608567a56d3e
Create Date: 2017-12-25 06:58:45.182863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2ec879943f'
down_revision = '608567a56d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration', 'client_secret')
    op.drop_column('integration', 'oauth_token_exchange_url')
    op.drop_column('integration', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration', sa.Column('client_id', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    op.add_column('integration', sa.Column('oauth_token_exchange_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('integration', sa.Column('client_secret', sa.VARCHAR(length=240), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
