"""empty message

Revision ID: 814ec150634c
Revises: 1d5588e7799d
Create Date: 2018-01-11 11:31:04.669922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814ec150634c'
down_revision = '1d5588e7799d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=360), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=240), nullable=True),
    sa.Column('author_icon', sa.String(length=240), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_sha'), 'commit', ['sha'], unique=True)
    op.add_column(u'deployment', sa.Column('commit_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_deployment_commit_id'), 'deployment', ['commit_id'], unique=False)
    op.create_foreign_key(None, 'deployment', 'commit', ['commit_id'], ['id'])
    op.drop_column(u'deployment', 'sha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'deployment', sa.Column('sha', sa.VARCHAR(length=360), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deployment', type_='foreignkey')
    op.drop_index(op.f('ix_deployment_commit_id'), table_name='deployment')
    op.drop_column(u'deployment', 'commit_id')
    op.drop_index(op.f('ix_commit_sha'), table_name='commit')
    op.drop_table('commit')
    # ### end Alembic commands ###
