"""empty message

Revision ID: 8610df01cf2a
Revises: a454737f5caf
Create Date: 2018-01-25 20:24:11.305077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8610df01cf2a'
down_revision = 'a454737f5caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    # ### end Alembic commands ###
