"""empty message

Revision ID: cdf19e6c2884
Revises: 80a1d6642f9e
Create Date: 2017-11-18 15:41:22.708794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf19e6c2884'
down_revision = '80a1d6642f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'status')
    # ### end Alembic commands ###
