"""empty message

Revision ID: d22ca886b990
Revises: f75ea9146e93
Create Date: 2018-02-02 09:50:38.353511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22ca886b990'
down_revision = 'f75ea9146e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph', 'x_axis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('graph', 'y_axis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph', 'y_axis',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('graph', 'x_axis',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
