"""empty message

Revision ID: e6bf493e4e5c
Revises: 
Create Date: 2017-11-28 14:34:42.812288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6bf493e4e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_slug'), 'team', ['slug'], unique=True)
    op.create_index(op.f('ix_team_uid'), 'team', ['uid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('hashed_pw', sa.String(length=120), nullable=True),
    sa.Column('verification_status', sa.Integer(), nullable=True),
    sa.Column('verification_secret', sa.String(length=64), nullable=True),
    sa.Column('reset_pw_secret', sa.String(length=64), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=True)
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=360), nullable=False),
    sa.Column('ns_addresses', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('hosted_zone_id', sa.String(length=120), nullable=True),
    sa.Column('zones', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('master_type', sa.String(length=120), nullable=True),
    sa.Column('node_type', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('validated', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_team_id'), 'cluster', ['team_id'], unique=False)
    op.create_index(op.f('ix_cluster_uid'), 'cluster', ['uid'], unique=True)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=True),
    sa.Column('elb', sa.String(length=240), nullable=True),
    sa.Column('domain', sa.String(length=360), nullable=True),
    sa.Column('git_repo', sa.String(length=240), nullable=True),
    sa.Column('image_repo_owner', sa.String(length=120), nullable=True),
    sa.Column('image_version', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('sha', sa.String(length=360), nullable=True),
    sa.Column('deploy_name', sa.String(length=360), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_slug'), 'prediction', ['slug'], unique=False)
    op.create_index(op.f('ix_prediction_team_id'), 'prediction', ['team_id'], unique=False)
    op.create_index(op.f('ix_prediction_uid'), 'prediction', ['uid'], unique=True)
    op.create_table('team_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_user_team_id'), 'team_user', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_user_user_id'), 'team_user', ['user_id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_user_id'), 'token', ['user_id'], unique=False)
    op.create_table('bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucket_cluster_id'), 'bucket', ['cluster_id'], unique=False)
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_index(op.f('ix_bucket_cluster_id'), table_name='bucket')
    op.drop_table('bucket')
    op.drop_index(op.f('ix_token_user_id'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_team_user_user_id'), table_name='team_user')
    op.drop_index(op.f('ix_team_user_team_id'), table_name='team_user')
    op.drop_table('team_user')
    op.drop_index(op.f('ix_prediction_uid'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_team_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_slug'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_cluster_uid'), table_name='cluster')
    op.drop_index(op.f('ix_cluster_team_id'), table_name='cluster')
    op.drop_table('cluster')
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_team_uid'), table_name='team')
    op.drop_index(op.f('ix_team_slug'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
