"""empty message

Revision ID: f74603988617
Revises: dcf3b61c5336
Create Date: 2017-12-16 22:09:17.944533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74603988617'
down_revision = 'dcf3b61c5336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), server_default='f', nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_prediction_id'), 'dataset', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_dataset_slug'), 'dataset', ['slug'], unique=False)
    op.create_index(op.f('ix_dataset_uid'), 'dataset', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_uid'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_slug'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_prediction_id'), table_name='dataset')
    op.drop_table('dataset')
    # ### end Alembic commands ###
