"""empty message

Revision ID: f75ea9146e93
Revises: 3265dc895d3e
Create Date: 2018-01-31 20:36:03.092894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75ea9146e93'
down_revision = '3265dc895d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_data_group', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_data_group', 'color')
    # ### end Alembic commands ###
