"""empty message

Revision ID: f890544816ca
Revises: cdf19e6c2884
Create Date: 2017-11-19 16:29:15.040905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f890544816ca'
down_revision = 'cdf19e6c2884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('hosted_zone_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'hosted_zone_id')
    # ### end Alembic commands ###
